services:
  php:
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.4
    container_name: app-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  vite:
    image: node:22
    working_dir: /var/www
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    volumes:
      - ./:/var/www
    command: npm run dev
    tty: true
    stdin_open: true
    ports:
      - "5173:5173"

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: php artisan queue:listen
    depends_on:
      - mysql
      - redis

  reverb:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: php artisan reverb:start --debug --host=0.0.0.0
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis

  schedule:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: php artisan schedule:work
    depends_on:
      - mysql
      - redis

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql

volumes:
  mysql-data:
